# Dovecot main configuration for SecureMailScope Synthetic Lab
protocols = imap pop3
listen = *
base_dir = /var/run/dovecot/

log_path = /var/log/dovecot.log
info_log_path = /var/log/dovecot.log
debug_log_path = /var/log/dovecot.log

ssl = yes
ssl_cert = </certs/server_valid.crt
ssl_key = </certs/server_valid.key
ssl_min_protocol = TLSv1.2

disable_plaintext_auth = no
auth_mechanisms = plain login

passdb {
  driver = passwd-file
  args = scheme=PLAIN username_format=%u /etc/dovecot/users
}

userdb {
  driver = static
  args = uid=1000 gid=1000 home=/var/mail/%u
}
